pipeline:
  frontend:
    group: build
    image: node:8
    commands:
      - npm install
      - npm run lint
      # - npm run test
      - npm run build
  publish:
    image: appleboy/drone-scp
    repo: ben/lnb-client
    host: latenight.blue
    username: lnb
    secrets:
      - source: lnb_ssh_key
        target: scp_key
    source: dist/*
    target: /home/lnb/lnb-server/static/latenight.blue
    strip_components: 1
    rm: true
    when:
      event: tag
      status: success